apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test1
  labels:
    tier: app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app-php
  template:
    metadata:
      labels:
        app: app-php
        tier: app-php
    spec:
      containers:
        - name: app
          image: bretgauer1obit/app-test:v2
          volumeMounts:
            - mountPath: /var/www/html
              name: contents
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /application/. /var/www/html" ]
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: contents

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: contents
          emptyDir: { }

        - name: nginx-config
          configMap:
            name: nginx-config