apiVersion: v1
kind: Pod
metadata:
  name: app-test1
  labels:
    tier: app-php
spec:
  containers:
    - image: bretgauer1obit/app-test:v2
      name: app
      volumeMounts:
          - mountPath: /var/www/html
            name: contents

      lifecycle:
        postStart:
          exec:
              command: [ "/bin/sh", "-c", "cp -r /application/. /var/www/html" ]

    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/html
          name: contents

        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf



  volumes:
    - name: contents
      emptyDir: { }

    - name: nginx-config
      configMap:
        name: nginx-config