apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
      {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Chart.Name }}-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location ~ \.html$ {
         root /var/www/html;
         index index.html;
      }
    
      location / {
          include fastcgi_params;
          fastcgi_split_path_info ^(.+\?)(/.+)$;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
          fastcgi_param SCRIPT_NAME /var/www/html/index.php;
          fastcgi_param QUERY_STRING $query_string;
          fastcgi_param PATH_INFO $fastcgi_path_info;    
          fastcgi_connect_timeout 300s;
          fastcgi_pass 127.0.0.1:9000;
      }
    }
