apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-test1
  labels:
    tier: {{ .Chart.Name }}-php
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ .Chart.Name }}-php
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-php
        tier: {{ .Chart.Name }}-php
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagepullpolicy }}
          volumeMounts:
            - mountPath: /var/www/html
              name: contents
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /application/. /var/www/html" ]
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: contents

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: contents
          emptyDir: { }

        - name: nginx-config
          configMap:
            name: nginx-config